a:2:{s:7:"current";a:8:{s:4:"date";a:2:{s:7:"created";i:1497920626;s:8:"modified";i:1497920626;}s:7:"creator";s:11:"Tracy Kuhrt";s:4:"user";s:6:"tkuhrt";s:11:"last_change";a:7:{s:4:"date";i:1497920626;s:2:"ip";s:13:"173.22.224.10";s:4:"type";s:1:"C";s:2:"id";s:30:"projects:fabric:error-handling";s:4:"user";s:6:"tkuhrt";s:3:"sum";s:25:"Moved from error-handling";s:5:"extra";s:0:"";}s:5:"title";s:24:"Error handling framework";s:8:"internal";a:2:{s:5:"cache";b:1;s:3:"toc";b:1;}s:11:"description";a:1:{s:8:"abstract";s:354:"Error handling framework

Usage instructions

The new error handling framework should be used in place of all calls to
fmt.Errorf() or Errors.new(). Using this framework will provide error codes to
check against as well as the option to generate a callstack that will be
appended to the error message when logging.error is set to debug in
peer/core.yaml.";}s:8:"relation";a:1:{s:10:"firstimage";s:0:"";}}s:10:"persistent";a:4:{s:4:"date";a:1:{s:7:"created";i:1497920626;}s:7:"creator";s:11:"Tracy Kuhrt";s:4:"user";s:6:"tkuhrt";s:11:"last_change";a:7:{s:4:"date";i:1497920626;s:2:"ip";s:13:"173.22.224.10";s:4:"type";s:1:"C";s:2:"id";s:30:"projects:fabric:error-handling";s:4:"user";s:6:"tkuhrt";s:3:"sum";s:25:"Moved from error-handling";s:5:"extra";s:0:"";}}}